version: 2.0

jobs:
  build:
    docker:
      - image: zeling/ubuntu:19.04-llvm-8
    steps:
      - checkout
      - run:
          name: Prepare build directory
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cd build && make
      - persist_to_workspace:
          root: .
          paths: build

  test:
    docker:
      - image: zeling/ubuntu:19.04-llvm-8
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: ./build/test_main

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
